name: libdoip CI

on: push

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - name: Build
              run: ./makeindocker.sh
            - name: Test
              run: ./runtestindocker.sh
        